//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathfinderPortraitManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextVariables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextVariables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PathfinderPortraitManager.Properties.TextVariables", typeof(TextVariables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BUTTON_BACKTOFILE {
            get {
                return ResourceManager.GetString("BUTTON_BACKTOFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string BUTTON_CHANGESELECTED {
            get {
                return ResourceManager.GetString("BUTTON_CHANGESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BUTTON_CREATEPORTRAIT {
            get {
                return ResourceManager.GetString("BUTTON_CREATEPORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BUTTON_DELETESELECTED {
            get {
                return ResourceManager.GetString("BUTTON_DELETESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string BUTTON_EXIT {
            get {
                return ResourceManager.GetString("BUTTON_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string BUTTON_HINT {
            get {
                return ResourceManager.GetString("BUTTON_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string BUTTON_LOAD {
            get {
                return ResourceManager.GetString("BUTTON_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose local.
        /// </summary>
        internal static string BUTTON_LOCALPORTRAIT {
            get {
                return ResourceManager.GetString("BUTTON_LOCALPORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Folder.
        /// </summary>
        internal static string BUTTON_TOEXRACT {
            get {
                return ResourceManager.GetString("BUTTON_TOEXRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Portrait.
        /// </summary>
        internal static string BUTTON_TOFILEPAGE {
            get {
                return ResourceManager.GetString("BUTTON_TOFILEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Gallery.
        /// </summary>
        internal static string BUTTON_TOGALLERY {
            get {
                return ResourceManager.GetString("BUTTON_TOGALLERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BUTTON_TOMAINPAGE {
            get {
                return ResourceManager.GetString("BUTTON_TOMAINPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string BUTTON_TOSCALEPAGE {
            get {
                return ResourceManager.GetString("BUTTON_TOSCALEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose web.
        /// </summary>
        internal static string BUTTON_WEBPORTRAIT {
            get {
                return ResourceManager.GetString("BUTTON_WEBPORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Extract page.
        /// </summary>
        internal static string HINT_EXTRACTPAGE {
            get {
                return ResourceManager.GetString("HINT_EXTRACTPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the file page. Here you can choose which image to use as portrait. You can load a local image by clicking the button or the image, or simply drag and drop into the picture. As well, you can load a web picture by clicking the button..
        /// </summary>
        internal static string HINT_FILEPAGE {
            get {
                return ResourceManager.GetString("HINT_FILEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Scale page.
        /// </summary>
        internal static string HINT_SCALEPAGE {
            get {
                return ResourceManager.GetString("HINT_SCALEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artemii &quot;Zeight&quot; Saganenko© 2023.
        /// </summary>
        internal static string LABEL_COPY {
            get {
                return ResourceManager.GetString("LABEL_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LABEL_UNNAMED1 {
            get {
                return ResourceManager.GetString("LABEL_UNNAMED1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LABEL_UNNAMED2 {
            get {
                return ResourceManager.GetString("LABEL_UNNAMED2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LABEL_UNNAMED3 {
            get {
                return ResourceManager.GetString("LABEL_UNNAMED3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop, input, or copy the url of an existing image. The url address must lead to an accessible web-source..
        /// </summary>
        internal static string LABEL_URLDIALOG {
            get {
                return ResourceManager.GetString("LABEL_URLDIALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MESG_ERRORNOTCREATED {
            get {
                return ResourceManager.GetString("MESG_ERRORNOTCREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MESG_FOLDERNOTFOUND {
            get {
                return ResourceManager.GetString("MESG_FOLDERNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not load any images. However, you still can use the default image. Proceed with default?.
        /// </summary>
        internal static string MESG_NOIMAGE {
            get {
                return ResourceManager.GetString("MESG_NOIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MESG_WEBNOTLOADED {
            get {
                return ResourceManager.GetString("MESG_WEBNOTLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TEXT_CHARPORTRAIT {
            get {
                return ResourceManager.GetString("TEXT_CHARPORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TEXT_GAMEPORTRAIT {
            get {
                return ResourceManager.GetString("TEXT_GAMEPORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All images.
        /// </summary>
        internal static string TEXT_IMAGEFILTER {
            get {
                return ResourceManager.GetString("TEXT_IMAGEFILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TEXT_LRGPORTRAIT {
            get {
                return ResourceManager.GetString("TEXT_LRGPORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TEXT_MEDPORTRAIT {
            get {
                return ResourceManager.GetString("TEXT_MEDPORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose image.
        /// </summary>
        internal static string TEXT_OPENFILE {
            get {
                return ResourceManager.GetString("TEXT_OPENFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TEXT_SMLPORTRAIT {
            get {
                return ResourceManager.GetString("TEXT_SMLPORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TEXT_STATSPORTRAIT {
            get {
                return ResourceManager.GetString("TEXT_STATSPORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input URL here.
        /// </summary>
        internal static string TEXTBOX_URL_INPUT {
            get {
                return ResourceManager.GetString("TEXTBOX_URL_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect URL.
        /// </summary>
        internal static string TEXTBOX_URL_WRONG {
            get {
                return ResourceManager.GetString("TEXTBOX_URL_WRONG", resourceCulture);
            }
        }
    }
}
