//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathfinderPortraitManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextVariables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextVariables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PathfinderPortraitManager.Properties.TextVariables", typeof(TextVariables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BUTTON_BACKTOFILE {
            get {
                return ResourceManager.GetString("BUTTON_BACKTOFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string BUTTON_CHANGESELECTED {
            get {
                return ResourceManager.GetString("BUTTON_CHANGESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string BUTTON_CREATENEW {
            get {
                return ResourceManager.GetString("BUTTON_CREATENEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string BUTTON_CREATEPORTRAIT {
            get {
                return ResourceManager.GetString("BUTTON_CREATEPORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BUTTON_DELETESELECTED {
            get {
                return ResourceManager.GetString("BUTTON_DELETESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string BUTTON_EXIT {
            get {
                return ResourceManager.GetString("BUTTON_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string BUTTON_HINT {
            get {
                return ResourceManager.GetString("BUTTON_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string BUTTON_LOAD {
            get {
                return ResourceManager.GetString("BUTTON_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose local.
        /// </summary>
        internal static string BUTTON_LOCALPORTRAIT {
            get {
                return ResourceManager.GetString("BUTTON_LOCALPORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string BUTTON_MENU {
            get {
                return ResourceManager.GetString("BUTTON_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string BUTTON_OPEN {
            get {
                return ResourceManager.GetString("BUTTON_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Folder.
        /// </summary>
        internal static string BUTTON_TOEXRACT {
            get {
                return ResourceManager.GetString("BUTTON_TOEXRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Portrait.
        /// </summary>
        internal static string BUTTON_TOFILEPAGE {
            get {
                return ResourceManager.GetString("BUTTON_TOFILEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Gallery.
        /// </summary>
        internal static string BUTTON_TOGALLERY {
            get {
                return ResourceManager.GetString("BUTTON_TOGALLERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BUTTON_TOMAINPAGE {
            get {
                return ResourceManager.GetString("BUTTON_TOMAINPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string BUTTON_TOSCALEPAGE {
            get {
                return ResourceManager.GetString("BUTTON_TOSCALEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose web.
        /// </summary>
        internal static string BUTTON_WEBPORTRAIT {
            get {
                return ResourceManager.GetString("BUTTON_WEBPORTRAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Extract page.
        /// </summary>
        internal static string HINT_EXTRACTPAGE {
            get {
                return ResourceManager.GetString("HINT_EXTRACTPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the file page. Here you can choose which image to use as portrait. You can load a local image by clicking the button or the image, or simply drag and drop into the picture. As well, you can load a web picture by clicking the button..
        /// </summary>
        internal static string HINT_FILEPAGE {
            get {
                return ResourceManager.GetString("HINT_FILEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a page to scale and crop the image as you see fit. Use the mouse wheel to zoom the image in and out. Double-click the image to restore it to original state. Drag image to adjust it. Click &quot;Create&quot; to add a new portrait. They will be almost exact copies of the images you set up in frames in this page. Press &quot;Back&quot; to return to previous page..
        /// </summary>
        internal static string HINT_SCALEPAGE {
            get {
                return ResourceManager.GetString("HINT_SCALEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artemii &quot;Zeight&quot; Saganenko© 2023.
        /// </summary>
        internal static string LABEL_COPY {
            get {
                return ResourceManager.GetString("LABEL_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Considering you reached this stage. It is rather a problem with game directory. Check directory existence shown above. Create it if needed. .
        /// </summary>
        internal static string LABEL_CREATEDERROR {
            get {
                return ResourceManager.GetString("LABEL_CREATEDERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The portrait was successfully created in the working directory, the location of which is shown above. It is now available to use in the game. Click &quot;New&quot; to create another one, &quot;open&quot; to show the directory, and &quot;menu&quot; to return..
        /// </summary>
        internal static string LABEL_CREATEDOK {
            get {
                return ResourceManager.GetString("LABEL_CREATEDOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string LABEL_LARGEIMG {
            get {
                return ResourceManager.GetString("LABEL_LARGEIMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character portrait.
        /// </summary>
        internal static string LABEL_LARGEIMG2 {
            get {
                return ResourceManager.GetString("LABEL_LARGEIMG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string LABEL_MEDIUMIMG {
            get {
                return ResourceManager.GetString("LABEL_MEDIUMIMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills portrait.
        /// </summary>
        internal static string LABEL_MEDIUMIMG2 {
            get {
                return ResourceManager.GetString("LABEL_MEDIUMIMG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string LABEL_SMALLIMG {
            get {
                return ResourceManager.GetString("LABEL_SMALLIMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameplay portrait.
        /// </summary>
        internal static string LABEL_SMALLIMG2 {
            get {
                return ResourceManager.GetString("LABEL_SMALLIMG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop, input, or copy the url of an existing image. The url address must lead to an accessible web-source..
        /// </summary>
        internal static string LABEL_URLDIALOG {
            get {
                return ResourceManager.GetString("LABEL_URLDIALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MESG_ERRORNOTCREATED {
            get {
                return ResourceManager.GetString("MESG_ERRORNOTCREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MESG_FOLDERNOTFOUND {
            get {
                return ResourceManager.GetString("MESG_FOLDERNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not load any images. However, you still can use the default image. Proceed with default?.
        /// </summary>
        internal static string MESG_NOIMAGE {
            get {
                return ResourceManager.GetString("MESG_NOIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MESG_WEBNOTLOADED {
            get {
                return ResourceManager.GetString("MESG_WEBNOTLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All images.
        /// </summary>
        internal static string TEXT_IMAGEFILTER {
            get {
                return ResourceManager.GetString("TEXT_IMAGEFILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose image.
        /// </summary>
        internal static string TEXT_OPENFILE {
            get {
                return ResourceManager.GetString("TEXT_OPENFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input URL here.
        /// </summary>
        internal static string TEXTBOX_URL_INPUT {
            get {
                return ResourceManager.GetString("TEXTBOX_URL_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect URL.
        /// </summary>
        internal static string TEXTBOX_URL_WRONG {
            get {
                return ResourceManager.GetString("TEXTBOX_URL_WRONG", resourceCulture);
            }
        }
    }
}
