//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathfinderPortraitManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextVariables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextVariables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PathfinderPortraitManager.Properties.TextVariables", typeof(TextVariables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string btnBackToFilePage {
            get {
                return ResourceManager.GetString("btnBackToFilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string btnChange {
            get {
                return ResourceManager.GetString("btnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string btnCreatePortrait {
            get {
                return ResourceManager.GetString("btnCreatePortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDeletePortrait {
            get {
                return ResourceManager.GetString("btnDeletePortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract folder.
        /// </summary>
        internal static string btnExtract {
            get {
                return ResourceManager.GetString("btnExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string btnHintOnFilePage {
            get {
                return ResourceManager.GetString("btnHintOnFilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string btnHintOnFolder {
            get {
                return ResourceManager.GetString("btnHintOnFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string btnHintOnScalePage {
            get {
                return ResourceManager.GetString("btnHintOnScalePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string btnLabelUnnamed1 {
            get {
                return ResourceManager.GetString("btnLabelUnnamed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string btnLabelUnnamed2 {
            get {
                return ResourceManager.GetString("btnLabelUnnamed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string btnLabelUnnamed3 {
            get {
                return ResourceManager.GetString("btnLabelUnnamed3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string btnLoad {
            get {
                return ResourceManager.GetString("btnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose local.
        /// </summary>
        internal static string btnLocalPortraitLoad {
            get {
                return ResourceManager.GetString("btnLocalPortraitLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create portrait.
        /// </summary>
        internal static string btnToFilePage {
            get {
                return ResourceManager.GetString("btnToFilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse gallery.
        /// </summary>
        internal static string btnToGalleryPage {
            get {
                return ResourceManager.GetString("btnToGalleryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string btnToMainPage {
            get {
                return ResourceManager.GetString("btnToMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string btnToScalePage {
            get {
                return ResourceManager.GetString("btnToScalePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose web.
        /// </summary>
        internal static string btnWebPortraitLoad {
            get {
                return ResourceManager.GetString("btnWebPortraitLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string charPortrait {
            get {
                return ResourceManager.GetString("charPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop, input, or copy the URL of an existing image. The URL address must lead to an accessible web-source..
        /// </summary>
        internal static string dialURL {
            get {
                return ResourceManager.GetString("dialURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gamePortrait {
            get {
                return ResourceManager.GetString("gamePortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string hintExtractPage {
            get {
                return ResourceManager.GetString("hintExtractPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string hintFilePage {
            get {
                return ResourceManager.GetString("hintFilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string hintFolderPage {
            get {
                return ResourceManager.GetString("hintFolderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string hintScalingPage {
            get {
                return ResourceManager.GetString("hintScalingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All images.
        /// </summary>
        internal static string imageFilter {
            get {
                return ResourceManager.GetString("imageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string inquiryNoImages {
            get {
                return ResourceManager.GetString("inquiryNoImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artemii &quot;Zeight&quot; Saganenko ©2023.
        /// </summary>
        internal static string labelCopyright {
            get {
                return ResourceManager.GetString("labelCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string lrgPortrait {
            get {
                return ResourceManager.GetString("lrgPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string medPortrait {
            get {
                return ResourceManager.GetString("medPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string mesgCannotLoad {
            get {
                return ResourceManager.GetString("mesgCannotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string mesgNotFound {
            get {
                return ResourceManager.GetString("mesgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string mesgNotLoaded {
            get {
                return ResourceManager.GetString("mesgNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open local file.
        /// </summary>
        internal static string openFileTitle {
            get {
                return ResourceManager.GetString("openFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string smlPortrait {
            get {
                return ResourceManager.GetString("smlPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string statsPortrait {
            get {
                return ResourceManager.GetString("statsPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input URL here.
        /// </summary>
        internal static string txtbxCopy {
            get {
                return ResourceManager.GetString("txtbxCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect URL.
        /// </summary>
        internal static string txtbxIncorrect {
            get {
                return ResourceManager.GetString("txtbxIncorrect", resourceCulture);
            }
        }
    }
}
