//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathfinderPortraitManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class UseStamps : global::System.Configuration.ApplicationSettingsBase {
        
        private static UseStamps defaultInstance = ((UseStamps)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UseStamps())));
        
        public static UseStamps Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isFirstPortrait {
            get {
                return ((bool)(this["isFirstPortrait"]));
            }
            set {
                this["isFirstPortrait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isFirstScaling {
            get {
                return ((bool)(this["isFirstScaling"]));
            }
            set {
                this["isFirstScaling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isFirstExtract {
            get {
                return ((bool)(this["isFirstExtract"]));
            }
            set {
                this["isFirstExtract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isFirstGallery {
            get {
                return ((bool)(this["isFirstGallery"]));
            }
            set {
                this["isFirstGallery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isFirstAny {
            get {
                return ((bool)(this["isFirstAny"]));
            }
            set {
                this["isFirstAny"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NotRevealed")]
        public string isAwareNPC {
            get {
                return ((string)(this["isAwareNPC"]));
            }
            set {
                this["isAwareNPC"] = value;
            }
        }
    }
}
